[package]
name = "echo_bot"
version = "0.1.0"
authors = ["Daiki Mizukami <mizukami1113@gmail.com>"]
publish = false

[dependencies]
futures = "0.1.4"
hyper = "0.11"
serde_json = "1"
tokio-core = "0.1"
tweetust = "0.7"
twitter-stream = { path = "../../twitter-stream", features = ["tweetust"] }
