branches:
  only:
  - master
  - /^v\d+\.\d+\.x$/
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.21.0
matrix:
  allow_failures:
    - rust: nightly
    - rust: 1.21.0
script:
  - |
    cd $CRATE
    if [ -z "$FEATURES" ]; then
      cargo build --verbose &&
      cargo test --verbose
    else
      cargo check --verbose --features=$FEATURES
    fi &&
    cargo doc --verbose --no-deps --no-default-features --features=$FEATURES
env:
  - CRATE=twitter-stream
#  - CRATE=twitter-stream FEATURES=tls-rustls
  - CRATE=twitter-stream FEATURES=tls-openssl
  - CRATE=twitter-stream FEATURES=egg-mode
  - CRATE=twitter-stream FEATURES=tweetust
  - CRATE=twitter-stream-message
