branches:
  only:
  - master
  - /^v\d+\.\d+\.x$/
language: rust
rust:
  # - stable
  # - beta
  - nightly-2019-09-05
  - 1.30.0
matrix:
  allow_failures:
    # - rust: nightly
    - rust: 1.30.0
script:
  - |
    if [ "$FEATURES" = tls ]; then
      cargo build --verbose --no-default-features --features=$FEATURES &&
      cargo test --verbose --no-default-features --features=$FEATURES
    else
      cargo check --verbose --no-default-features --features=$FEATURES
    fi
env:
  - FEATURES=
  - FEATURES=runtime
  - FEATURES=tls
  - FEATURES=egg-mode,tweetust
