language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --no-default-features --features=$FEATURES
  - cargo test --verbose --no-default-features --features=$FEATURES
  - cargo doc --verbose --no-deps --no-default-features --features=$FEATURES
env:
  - FEATURES=
  - FEATURES=egg-mode
  - FEATURES=tweetust
  - FEATURES=tls-native-tls
  - FEATURES=tls-openssl
  - FEATURES=tls-rustls
